<#import "webSocketMaster.ftlh" as m>
<@m.websockmaster>
<div class="container">
    <div class="row">
        <div class="col-8 offset-2">
            <div class="text-center">
                <h1>
                    Lycanthrope
                </h1>
                <div id="lobbytable" class="d-flex flex-column">

                </div>
            </div>
        </div>
    </div>
</div>
</@m.websockmaster>