<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="text-center">
                <h1>
                    Lycanthrope
                </h1>
                <hr>
                <button class="btn btn-block btn-primary" onclick="getCreateLobbyView()">Create Lobby</button>
                <div id="lobbytable" class="d-flex flex-column">

                </div>
            </div>
        </div>
    </div>
</div>